apiVersion: v1
kind: Secret
metadata:
  name: docker-registry1
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: '{"auths": {"albertsonstestacr.azurecr.io": {"username": "AlbertsonsTestACR", "password": "KC/epsjApdAf/BYgMDmAXcT0jToMmfCRH2sFCaohu3+ACRBodoSr"}}}'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    db : db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      db: db
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        db: db
    spec:
      imagePullSecrets:
        - name: docker-registry1
      containers:
        - image: albertsonstestacr.azurecr.io/db:latest
          name: db
          ports:
            - containerPort: 3306
          resources: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
   db: db
  name: db
spec:
  ports:
    - name: "mysql-port"
      port: 3306
      targetPort: 3306
  selector:
   db: db
