apiVersion: v1
kind: Secret
metadata:
  name: dockerregistry
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJhbGJlcnRzb25zdGVzdGFjci5henVyZWNyLmlvIjp7InVzZXJuYW1lIjoiQWxiZXJ0c29uc1Rlc3RBU1IiLCJwYXNzd29yZCI6IktDL2Vwc2pBcGRBZi9CWWdNRG1BWGNUMGpUb01tZkNSSDJzRkNhb2h1MysBQ1JCb2RvU3IifX19
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    db : db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      db: db
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        db: db
    spec:
      imagePullSecrets:
        - name: containerregistry
      containers:
        - image: albertsonstestacr.azurecr.io/db:latest
          name: db
          ports:
            - containerPort: 3306
          resources: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
   db: db
  name: db
spec:
  ports:
    - name: "mysql-port"
      port: 3306
      targetPort: 3306
  selector:
   db: db
