apiVersion: v1
kind: Secret
metadata:
  name: docker-registry2
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: '{"auths": {"albertsonstestacr.azurecr.io": {"username": "AlbertsonsTestACR", "password": "KC/epsjApdAf/BYgMDmAXcT0jToMmfCRH2sFCaohu3+ACRBodoSr"}}}'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      imagePullSecrets:
        - name: docker-registry2
      containers:
        - image: albertsonstestacr.azurecr.io/web:latest
          name: web
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
  name: web
spec:
  #type: NodePort
  type: LoadBalancer
  ports:
    - name: "web-port"
      port: 8080
      targetPort: 8080
      #nodePort: 30510
  selector:
    app: web
