apiVersion: v1
kind: Secret
metadata:
  name: dockerregistry
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJhbGJlcnRzb25zdGVzdGFjci5henVyZWNyLmlvIjp7InVzZXJuYW1lIjoiQWxiZXJ0c29uc1Rlc3RBU1IiLCJwYXNzd29yZCI6IktDL2Vwc2pBcGRBZi9CWWdNRG1BWGNUMGpUb01tZkNSSDJzRkNhb2h1MysBQ1JCb2RvU3IifX19
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      imagePullSecrets:
        - name: containerregistry
      containers:
        - image: albertsonstestacr.azurecr.io/web:latest
          name: web
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
  name: web
spec:
  #type: NodePort
  type: LoadBalancer
  ports:
    - name: "web-port"
      port: 8080
      targetPort: 8080
      #nodePort: 30510
  selector:
    app: web
